// R script generator - creates publication-quality map reproduction script
// Extracted from rExport.js for maintainability (~990 lines of R template)

// Generate R script that recreates the map view
const generateRScript = (colorBy, legendSettings) => {
  const isItalic = colorBy === 'species' || colorBy === 'subspecies' || colorBy === 'genus' || colorBy === 'scientific_name'

  return `# ════════════════════════════════════════════════════════════════════════════════
# Ithomiini Distribution Map - R Script for Publication-Quality Export
# Generated by Ithomiini Maps (https://rapidspeciation.github.io/ithomiini_maps/)
# ════════════════════════════════════════════════════════════════════════════════
#
# This script creates a map matching the web app preview with:
#   - Configurable basemap (via maptiles package)
#   - Styled legend with rounded corners and optional shapes
#   - Scale bar
#   - Point styling with stroke and optional shapes per group
#   - Display name formatting (predefined or custom)
#
# Output: PDF, PNG, and SVG files suitable for publications
# ════════════════════════════════════════════════════════════════════════════════

# ──────────────────────────────────────────────────────────────────────────────
# 1. INSTALL AND LOAD PACKAGES
# ──────────────────────────────────────────────────────────────────────────────

# All required packages
packages <- c(
  "sf",           # Spatial data handling
  "ggplot2",      # Plotting
  "dplyr",        # Data manipulation (pipes, joins)
  "tidyr",        # Data tidying (replace_na)
  "jsonlite",     # Read config files
  "maptiles",     # CartoDB basemap tiles
  "tidyterra",    # Plot raster tiles with ggplot2
  "ggspatial",    # Scale bar and north arrow
  "grid",         # Custom legend grobs
  "png",          # Read fallback basemap image
  "stringr"       # String manipulation for abbreviations
)

# Install missing packages
missing <- packages[!packages %in% installed.packages()[,"Package"]]
if (length(missing) > 0) {
  cat("Installing missing packages:", paste(missing, collapse = ", "), "\\n")
  install.packages(missing)
}

# Load all packages
invisible(lapply(packages, library, character.only = TRUE))

cat("All packages loaded\\n\\n")

# ──────────────────────────────────────────────────────────────────────────────
# 2. LOAD DATA
# ──────────────────────────────────────────────────────────────────────────────

cat("Loading exported data...\\n")

# Load spatial data and configs
points <- st_read("data.geojson", quiet = TRUE)
config <- fromJSON("view_config.json")
legend_data <- fromJSON("legend.json")

# Extract map bounds
bounds <- list(
  xmin = config$bounds$west,
  xmax = config$bounds$east,
  ymin = config$bounds$south,
  ymax = config$bounds$north
)

# Extract aspect ratio for dynamic output dimensions
aspect_ratio <- config$aspectRatio
if (is.null(aspect_ratio)) aspect_ratio <- 16/9  # fallback to 16:9

# Ensure 'species' column exists (may be named 'scientific_name' in GeoJSON)
if (!"species" %in% names(points) && "scientific_name" %in% names(points)) {
  points$species <- points$scientific_name
}

cat(sprintf("  %d points loaded\\n", nrow(points)))
cat(sprintf("  Bounds: [%.2f, %.2f] to [%.2f, %.2f]\\n",
            bounds$xmin, bounds$ymin, bounds$xmax, bounds$ymax))
cat(sprintf("  Aspect ratio: %.3f\\n", aspect_ratio))

# ──────────────────────────────────────────────────────────────────────────────
# 3. LOAD BASEMAP
# ──────────────────────────────────────────────────────────────────────────────

# Available basemap providers (change in STYLE section):
#   - "CartoDB.DarkMatter"   : Dark theme (default, matches web app) - supports retina
#   - "CartoDB.Positron"     : Light theme - supports retina
#   - "CartoDB.Voyager"      : Colored roads - supports retina
#   - "Stadia.AlidadeSmooth" : Smooth light theme - supports retina
#   - "Stadia.AlidadeSmoothDark" : Smooth dark theme - supports retina
#   - "OpenStreetMap"        : Standard OSM (no retina)
#   - "Esri.WorldImagery"    : Satellite imagery (no retina)
#   - "Esri.WorldTopoMap"    : Topographic (no retina)

# Note: STYLE is defined below, but we need basemap settings early
# CHANGE THESE to match your preferred basemap style and quality
basemap_provider <- "CartoDB.DarkMatter"
basemap_zoom <- NULL     # NULL = auto-detect, or set 1-18 (higher = more detail, slower)
basemap_retina <- TRUE   # TRUE = high-res tiles (2x) for CartoDB/Stadia providers

cat(sprintf("\\nLoading basemap (%s, retina=%s)...\\n", basemap_provider, basemap_retina))

# Create bounding box with small buffer for tile fetching
buffer <- 0.5
bbox_expanded <- st_bbox(c(
  xmin = bounds$xmin - buffer,
  ymin = bounds$ymin - buffer,
  xmax = bounds$xmax + buffer,
  ymax = bounds$ymax + buffer
), crs = 4326)

# Try to fetch tiles with high-resolution support
# retina=TRUE downloads 2x resolution tiles for supported providers (CartoDB, Stadia)
# zoom controls detail level (NULL = auto, higher = more detail but more tiles)
basemap <- NULL
tryCatch({
  basemap <- get_tiles(
    st_as_sfc(bbox_expanded),
    provider = basemap_provider,
    zoom = basemap_zoom,
    crop = TRUE,
    retina = basemap_retina
  )
  cat("  Basemap tiles loaded successfully\\n")
  if (basemap_retina) cat("  (High-resolution retina tiles)\\n")
}, error = function(e) {
  cat(sprintf("  Could not fetch tiles: %s\\n", e$message))
  cat("  Falling back to exported basemap.png\\n")
})

# Fallback to PNG if tiles failed
basemap_png <- NULL
if (is.null(basemap) && file.exists("basemap.png")) {
  basemap_png <- readPNG("basemap.png")
  cat("  Loaded basemap.png fallback\\n")
}

# ──────────────────────────────────────────────────────────────────────────────
# 4. PREPARE LEGEND DATA
# ──────────────────────────────────────────────────────────────────────────────

# Get max items from legend config (matches web app setting)
legend_max_items <- legend_data$maxItems
if (is.null(legend_max_items)) legend_max_items <- 15

# Create legend dataframe from exported items - PRESERVE ORDER from web app
# Do NOT re-sort - the items array is already in the correct display order
legend_df <- as.data.frame(legend_data$items)

# Add row index to preserve original order
legend_df$order_idx <- seq_len(nrow(legend_df))

cat(sprintf("\\nLegend: %d categories (showing max %d)\\n", nrow(legend_df), legend_max_items))

# ──────────────────────────────────────────────────────────────────────────────
# 5. DISPLAY NAME FORMATTING FUNCTIONS
# ──────────────────────────────────────────────────────────────────────────────
# These functions generate abbreviated names for scientific names.
# You can change display_name_format and prefix_format in the SETTINGS section below.
#
# Available display_name_format options:
#   "full"             - Full species name: "Mechanitis polymnia"
#   "firstLetterGenus" - First letter + epithet: "M. polymnia"
#   "syllableGenus"    - First syllable + epithet: "Mec. polymnia"
#   "custom"           - Use custom names from legend_data$displayNames
#
# Available prefix_format options:
#   "none"             - No prefix: "casabranca"
#   "firstLetterBoth"  - First letters: "M. p. casabranca"
#   "syllableBoth"     - First syllables: "Mec. pol. casabranca"
#   "custom"           - Use custom prefixes from legend_data$abbreviations

# Get first syllable of a word (smart syllable detection)
# Finds first vowel cluster, includes consonants after, minimum 2-3 chars
get_first_syllable <- function(word) {
  if (is.null(word) || nchar(word) <= 3) return(word)

  vowels <- c("a", "e", "i", "o", "u", "y")
  lower <- tolower(word)
  chars <- strsplit(lower, "")[[1]]

  result <- ""
  found_vowel <- FALSE
  vowel_ended <- FALSE


  for (i in seq_along(chars)) {
    char <- chars[i]
    is_vowel <- char %in% vowels

    if (!found_vowel) {
      result <- paste0(result, char)
      if (is_vowel) found_vowel <- TRUE
    } else if (!vowel_ended) {
      if (is_vowel) {
        result <- paste0(result, char)
      } else {
        vowel_ended <- TRUE
        result <- paste0(result, char)
        if (nchar(result) >= 3) break
      }
    } else {
      if (is_vowel) break
      result <- paste0(result, char)
      if (nchar(result) >= 4) break
    }
  }

  if (nchar(result) < 2) {
    result <- substr(lower, 1, min(3, nchar(lower)))
  }

  # Capitalize first letter and add period
  paste0(toupper(substr(result, 1, 1)), substr(result, 2, nchar(result)), ".")
}

# Generate abbreviation options for a species name
generate_abbreviations <- function(species_name) {
  if (is.null(species_name) || species_name == "") return(list(full = species_name))

  parts <- strsplit(trimws(species_name), "\\\\s+")[[1]]
  if (length(parts) < 2) {
    return(list(full = species_name, firstLetterGenus = species_name, syllableGenus = species_name))
  }

  genus <- parts[1]
  epithet <- paste(parts[-1], collapse = " ")
  first_epithet <- parts[2]

  # First letter abbreviations
  genus_first <- paste0(toupper(substr(genus, 1, 1)), ".")
  epithet_first <- paste0(tolower(substr(first_epithet, 1, 1)), ".")

  # Syllable abbreviations
  genus_syll <- get_first_syllable(genus)
  epithet_syll <- tolower(get_first_syllable(first_epithet))

  list(
    full = species_name,
    firstLetterGenus = paste(genus_first, epithet),
    firstLetterBoth = paste(genus_first, epithet_first),
    syllableGenus = paste(genus_syll, epithet),
    syllableBoth = paste(genus_syll, epithet_syll)
  )
}

# Apply display name format to a species name
apply_display_format <- function(species_name, format, custom_names = NULL) {
  if (format == "custom" && !is.null(custom_names) && species_name %in% names(custom_names)) {
    return(custom_names[[species_name]])
  }

  abbrevs <- generate_abbreviations(species_name)

  switch(format,
    "full" = abbrevs$full,
    "firstLetterGenus" = abbrevs$firstLetterGenus,
    "syllableGenus" = abbrevs$syllableGenus,
    abbrevs$full  # default
  )
}

# Apply prefix format to get abbreviation prefix
apply_prefix_format <- function(species_name, format, custom_abbrevs = NULL) {
  if (format == "none") return("")

  if (format == "custom" && !is.null(custom_abbrevs) && species_name %in% names(custom_abbrevs)) {
    return(custom_abbrevs[[species_name]])
  }

  abbrevs <- generate_abbreviations(species_name)

  switch(format,
    "firstLetterBoth" = abbrevs$firstLetterBoth,
    "syllableBoth" = abbrevs$syllableBoth,
    "none" = "",
    abbrevs$syllableBoth  # default
  )
}

# ──────────────────────────────────────────────────────────────────────────────
# 6. SHAPE UTILITIES FOR GGPLOT2
# ──────────────────────────────────────────────────────────────────────────────
# ggplot2 shape codes for common shapes:
#   21 = circle (filled, with border)      ●
#   22 = square (filled, with border)      ■
#   24 = triangle up (filled, with border) ▲
#   23 = diamond (filled, with border)     ◆
#
# To change a group's shape, modify the shape_map list below or
# change the shape column in the data.
#
# Shape reference (all filled shapes that support fill + color):
#   21 = circle, 22 = square, 23 = diamond, 24 = triangle up, 25 = triangle down

SHAPE_CODES <- list(
  circle = 21,    # Filled circle with border
  square = 22,    # Filled square with border
  triangle = 24,  # Filled triangle (up) with border
  rhombus = 23    # Filled diamond with border
)

# Convert shape name to ggplot2 shape code
get_shape_code <- function(shape_name) {
  code <- SHAPE_CODES[[shape_name]]
  if (is.null(code)) return(21)  # default to circle
  code
}

# ──────────────────────────────────────────────────────────────────────────────
# 7. LEGEND SETTINGS (from web app export)
# ──────────────────────────────────────────────────────────────────────────────

# Load legend settings from JSON
show_headers <- if (!is.null(legend_data$showHeaders)) legend_data$showHeaders else FALSE
group_by <- if (!is.null(legend_data$groupBy)) legend_data$groupBy else "species"
display_name_format <- if (!is.null(legend_data$displayNameFormat)) legend_data$displayNameFormat else "full"
prefix_format <- if (!is.null(legend_data$prefixFormat)) legend_data$prefixFormat else "syllableBoth"
shapes_enabled <- if (!is.null(legend_data$shapesEnabled)) legend_data$shapesEnabled else FALSE

# Custom names/abbreviations (if format is "custom")
custom_display_names <- legend_data$displayNames
custom_abbreviations <- legend_data$abbreviations

# Per-group shape assignments
group_shapes <- legend_data$groupShapes
if (is.null(group_shapes)) group_shapes <- list()

# Grouping information (species -> subspecies list)
legend_groups <- legend_data$groups
if (is.null(legend_groups)) legend_groups <- list()
use_grouped_legend <- group_by != "none" && length(legend_groups) > 0

# Legend position (normalized 0-1 coordinates)
# pos_x: left edge (0 = left, 1 = right)
# pos_y: TOP edge (0 = bottom, 1 = top) - note: this is TOP of legend, not bottom
legend_pos_x <- if (!is.null(legend_data$position$x)) legend_data$position$x else 0.02
legend_pos_y <- if (!is.null(legend_data$position$y)) legend_data$position$y else 0.92  # Default to near top

cat(sprintf("  Display name format: %s\\n", display_name_format))
cat(sprintf("  Prefix format: %s\\n", prefix_format))
cat(sprintf("  Show headers: %s\\n", show_headers))
cat(sprintf("  Group by: %s\\n", group_by))
cat(sprintf("  Shapes enabled: %s\\n", shapes_enabled))

# ──────────────────────────────────────────────────────────────────────────────
# 8. STYLING CONFIGURATION (easy to customize!)
# ──────────────────────────────────────────────────────────────────────────────

STYLE <- list(
  # Background - use "#1a1a2e" for dark themes, "#f5f5f5" for light themes
  bg_color = "#1a1a2e",

  # Points
  point_size = 2.5,
  point_alpha = 0.85,
  point_stroke_color = "white",
  point_stroke_alpha = 0.3,
  point_stroke_width = 0.5,

  # Legend - for light themes use: bg="#ffffff", border="#cccccc",
  #          title_color="#666666", text_color="#333333"
  # Note: legend_max_items is read from legend.json to match web app
  legend_bg = "#252540",
  legend_bg_alpha = 0.95,    # Transparency (0 = transparent, 1 = opaque)
  legend_border = "#3d3d5c",
  legend_title_color = "#888888",
  legend_text_color = "#e0e0e0",
  legend_font_size = 8,
  legend_title_size = 10,
  legend_width = 0.22,
  legend_padding = 0.015,
  legend_item_height = 0.028,

  # Scale bar - use "#333333" for light themes
  scale_bar_color = "#e0e0e0",

  # Output dimensions and quality
  # Note: DPI affects text, points, and vector elements but NOT basemap tile resolution.
  # For sharper basemaps, set basemap_retina=TRUE above (2x tiles) and/or increase basemap_zoom.
  # PDF/SVG are vector formats - points/legend are infinitely scalable, only basemap is raster.
  # Dimensions are calculated from aspect_ratio to match web app export
  base_size = 12,  # base size in inches (width for landscape, height for portrait)
  dpi = 300        # dots per inch (affects PNG rasterization, not PDF/SVG vector parts)
)

# Calculate output dimensions from aspect ratio (matches web app export)
if (aspect_ratio >= 1) {
  # Landscape or square: width is base_size
  output_width <- STYLE$base_size
  output_height <- STYLE$base_size / aspect_ratio
} else {
  # Portrait: height is base_size
  output_height <- STYLE$base_size
  output_width <- STYLE$base_size * aspect_ratio
}
cat(sprintf("  Output size: %.1f x %.1f inches\\n", output_width, output_height))

# ──────────────────────────────────────────────────────────────────────────────
# 9. CREATE LEGEND GROB (with rounded corners, shapes, and grouping)
# ──────────────────────────────────────────────────────────────────────────────

# Helper function to draw a shape in a grob
create_shape_grob <- function(x, y, shape, fill_color, stroke_color = "white", stroke_alpha = 0.3, size = 0.006) {
  shape_code <- get_shape_code(shape)

  # Use pointsGrob for consistent shape rendering
  pointsGrob(
    x = x, y = y,
    pch = shape_code,
    size = unit(size * 2, "npc"),
    gp = gpar(
      fill = fill_color,
      col = alpha(stroke_color, stroke_alpha),
      lwd = 0.5
    )
  )
}

create_legend <- function(items, title, max_items, italic = FALSE, style = STYLE,
                          pos_x = 0.02, pos_y = 0.92, use_shapes = FALSE) {
  # pos_x: left edge of legend (0-1, from left)
  # pos_y: TOP edge of legend (0-1, from bottom) - web app passes top position

  n_items <- min(nrow(items), max_items)
  has_more <- nrow(items) > max_items

  # Calculate dimensions
  title_h <- style$legend_item_height * 1.8
  content_h <- n_items * style$legend_item_height
  more_h <- if (has_more) style$legend_item_height * 1.2 else 0
  total_h <- title_h + content_h + more_h + style$legend_padding * 3

  # Find max label width using ONLY VISIBLE items (first n_items)
  visible_items <- items$label[1:n_items]
  max_label_len <- max(nchar(visible_items))
  # Tighter width calculation: 0.006 per character + small padding
  legend_w <- max(0.12, 0.006 * max_label_len + 0.05)

  # Position: convert from top-edge to bottom-edge for grob placement
  # pos_y is the TOP of the legend, y0 needs to be the BOTTOM
  x0 <- pos_x
  y0 <- pos_y - total_h  # Convert top position to bottom position

  grobs <- list()

  # Background with rounded corners
  grobs$bg <- roundrectGrob(
    x = x0, y = y0,
    width = legend_w, height = total_h,
    just = c("left", "bottom"),
    r = unit(8, "pt"),
    gp = gpar(
      fill = alpha(style$legend_bg, style$legend_bg_alpha),
      col = style$legend_border,
      lwd = 1
    )
  )

  # Title
  grobs$title <- textGrob(
    toupper(title),
    x = x0 + style$legend_padding,
    y = y0 + total_h - style$legend_padding - title_h/2,
    just = c("left", "center"),
    gp = gpar(
      col = style$legend_title_color,
      fontsize = style$legend_title_size,
      fontface = "bold"
    )
  )

  # Legend items
  for (i in seq_len(n_items)) {
    item_y <- y0 + total_h - title_h - style$legend_padding - (i - 0.5) * style$legend_item_height

    # Get shape for this item (default to circle)
    item_shape <- if (use_shapes && "shape" %in% names(items)) items$shape[i] else "circle"

    # Shape/dot indicator
    if (use_shapes && item_shape != "circle") {
      # Use shape grob for non-circle shapes
      grobs[[paste0("shape_", i)]] <- create_shape_grob(
        x = x0 + style$legend_padding + 0.012,
        y = item_y,
        shape = item_shape,
        fill_color = items$color[i]
      )
    } else {
      # Default circle
      grobs[[paste0("dot_", i)]] <- circleGrob(
        x = x0 + style$legend_padding + 0.012,
        y = item_y,
        r = 0.006,
        gp = gpar(
          fill = items$color[i],
          col = alpha("white", 0.3),
          lwd = 0.5
        )
      )
    }

    # Label
    grobs[[paste0("label_", i)]] <- textGrob(
      items$label[i],
      x = x0 + style$legend_padding + 0.028,
      y = item_y,
      just = c("left", "center"),
      gp = gpar(
        col = style$legend_text_color,
        fontsize = style$legend_font_size,
        fontface = if (italic) "italic" else "plain"
      )
    )
  }

  # "More" indicator if truncated
  if (has_more) {
    grobs$more <- textGrob(
      sprintf("+ %d more...", nrow(items) - max_items),
      x = x0 + style$legend_padding,
      y = y0 + style$legend_padding + more_h/2,
      just = c("left", "center"),
      gp = gpar(
        col = style$legend_title_color,
        fontsize = style$legend_font_size - 1,
        fontface = "italic"
      )
    )
  }

  do.call(grobTree, grobs)
}

# Create a grouped legend (species headers with subspecies underneath)
create_grouped_legend <- function(items, groups, title, max_items, style = STYLE,
                                   pos_x = 0.02, pos_y = 0.92, use_shapes = FALSE,
                                   show_headers = TRUE, display_names = NULL, group_shapes = NULL) {
  # pos_x: left edge of legend (0-1, from left)
  # pos_y: TOP edge of legend (0-1, from bottom)

  # Sort species alphabetically
  sorted_species <- sort(names(groups))

  # Count total items and calculate what fits in max_items
  total_items <- nrow(items)
  n_headers <- length(sorted_species)

  # Calculate how many items we can show (including headers if visible)
  items_shown <- 0
  headers_shown <- 0
  truncated <- FALSE

  for (sp in sorted_species) {
    subspecies_list <- groups[[sp]]
    if (show_headers) {
      if (items_shown + 1 + length(subspecies_list) <= max_items) {
        items_shown <- items_shown + length(subspecies_list)
        headers_shown <- headers_shown + 1
      } else {
        truncated <- TRUE
        break
      }
    } else {
      remaining <- max_items - items_shown
      if (remaining >= length(subspecies_list)) {
        items_shown <- items_shown + length(subspecies_list)
      } else {
        items_shown <- items_shown + remaining
        truncated <- TRUE
        break
      }
    }
  }

  # Calculate dimensions
  title_h <- style$legend_item_height * 1.8
  header_h <- if (show_headers) style$legend_item_height * 1.4 else 0
  item_h <- style$legend_item_height
  more_h <- if (truncated) style$legend_item_height * 1.2 else 0

  # Total content height
  content_h <- if (show_headers) {
    headers_shown * header_h + items_shown * item_h
  } else {
    items_shown * item_h
  }

  total_h <- title_h + content_h + more_h + style$legend_padding * 3

  # Find max label width - use tighter calculation for compact legend
  max_label_len <- max(nchar(items$label))
  if (show_headers && !is.null(display_names)) {
    max_header_len <- max(nchar(unlist(display_names)))
    max_label_len <- max(max_label_len, max_header_len)
  }
  # Tighter width calculation: 0.006 per character + small padding
  legend_w <- max(0.12, 0.006 * max_label_len + 0.05)

  # Position: convert from top-edge to bottom-edge
  x0 <- pos_x
  y0 <- pos_y - total_h

  grobs <- list()

  # Background
  grobs$bg <- roundrectGrob(
    x = x0, y = y0,
    width = legend_w, height = total_h,
    just = c("left", "bottom"),
    r = unit(8, "pt"),
    gp = gpar(
      fill = alpha(style$legend_bg, style$legend_bg_alpha),
      col = style$legend_border,
      lwd = 1
    )
  )

  # Title
  grobs$title <- textGrob(
    toupper(title),
    x = x0 + style$legend_padding,
    y = y0 + total_h - style$legend_padding - title_h/2,
    just = c("left", "center"),
    gp = gpar(
      col = style$legend_title_color,
      fontsize = style$legend_title_size,
      fontface = "bold"
    )
  )

  # Current Y position (starting after title)
  current_y <- y0 + total_h - title_h - style$legend_padding
  item_idx <- 1
  grob_idx <- 1

  for (sp in sorted_species) {
    subspecies_list <- groups[[sp]]
    if (items_shown <= 0) break

    # Get species display name
    sp_display <- if (!is.null(display_names) && sp %in% names(display_names)) {
      display_names[[sp]]
    } else {
      sp
    }

    # Get shape for this species
    sp_shape <- if (!is.null(group_shapes) && sp %in% names(group_shapes)) {
      group_shapes[[sp]]
    } else {
      "circle"
    }

    # Draw species header if enabled
    if (show_headers) {
      current_y <- current_y - header_h / 2

      # Shape indicator for species header
      if (use_shapes && sp_shape != "circle") {
        grobs[[paste0("header_shape_", grob_idx)]] <- create_shape_grob(
          x = x0 + style$legend_padding + 0.010,
          y = current_y,
          shape = sp_shape,
          fill_color = "transparent",
          stroke_color = style$legend_text_color,
          stroke_alpha = 0.6,
          size = 0.005
        )
      }

      # Species name (header)
      header_x <- if (use_shapes) x0 + style$legend_padding + 0.024 else x0 + style$legend_padding
      grobs[[paste0("header_", grob_idx)]] <- textGrob(
        sp_display,
        x = header_x,
        y = current_y,
        just = c("left", "center"),
        gp = gpar(
          col = style$legend_text_color,
          fontsize = style$legend_font_size,
          fontface = "bold.italic"
        )
      )

      current_y <- current_y - header_h / 2
      grob_idx <- grob_idx + 1
    }

    # Draw subspecies items
    for (subsp in subspecies_list) {
      if (item_idx > nrow(items)) break

      # Find this subspecies in items
      item_row <- which(items$label == subsp | grepl(paste0(subsp, "$"), items$label))[1]
      if (is.na(item_row)) next

      current_y <- current_y - item_h / 2

      # Color dot
      indent <- if (show_headers) 0.016 else 0
      grobs[[paste0("dot_", grob_idx)]] <- circleGrob(
        x = x0 + style$legend_padding + indent + 0.012,
        y = current_y,
        r = 0.006,
        gp = gpar(
          fill = items$color[item_row],
          col = alpha("white", 0.3),
          lwd = 0.5
        )
      )

      # Label
      grobs[[paste0("label_", grob_idx)]] <- textGrob(
        items$label[item_row],
        x = x0 + style$legend_padding + indent + 0.028,
        y = current_y,
        just = c("left", "center"),
        gp = gpar(
          col = style$legend_text_color,
          fontsize = style$legend_font_size,
          fontface = "italic"
        )
      )

      current_y <- current_y - item_h / 2
      item_idx <- item_idx + 1
      grob_idx <- grob_idx + 1

      if (item_idx > items_shown) break
    }

    if (item_idx > items_shown) break
  }

  # "More" indicator if truncated
  if (truncated) {
    remaining <- total_items - items_shown
    grobs$more <- textGrob(
      sprintf("+ %d more...", remaining),
      x = x0 + style$legend_padding,
      y = y0 + style$legend_padding + more_h/2,
      just = c("left", "center"),
      gp = gpar(
        col = style$legend_title_color,
        fontsize = style$legend_font_size - 1,
        fontface = "italic"
      )
    )
  }

  do.call(grobTree, grobs)
}

# ──────────────────────────────────────────────────────────────────────────────
# 10. APPLY PREFIX FORMAT TO LEGEND LABELS
# ──────────────────────────────────────────────────────────────────────────────

# Apply the selected prefix format to legend labels
# The 'label' column contains raw subspecies names, 'species' column has the parent species
cat("\\nFormatting legend labels...\\n")
cat(sprintf("  Prefix format: %s\\n", prefix_format))

if (prefix_format != "none" && "species" %in% names(legend_df)) {
  legend_df$display_label <- sapply(seq_len(nrow(legend_df)), function(i) {
    subspecies_name <- legend_df$label[i]
    species_name <- legend_df$species[i]

    # Get the prefix for this species
    prefix <- apply_prefix_format(species_name, prefix_format, custom_abbreviations)

    if (prefix == "" || is.null(prefix)) {
      subspecies_name
    } else {
      paste(prefix, subspecies_name)
    }
  })
} else {
  # No prefix - use raw label
  legend_df$display_label <- legend_df$label
}

# Update the label column with formatted labels for legend rendering
legend_df$label <- legend_df$display_label

# ──────────────────────────────────────────────────────────────────────────────
# 11. PREPARE DATA WITH SHAPES (if enabled)
# ──────────────────────────────────────────────────────────────────────────────

# Add shape column to points based on species (or other grouping)
if (shapes_enabled) {
  cat("\\nApplying shapes to data points...\\n")

  # Debug: show what group_shapes contains
  if (length(group_shapes) > 0) {
    cat("  Group shapes mapping:\\n")
    for (sp_name in names(group_shapes)) {
      cat(sprintf("    %s -> %s\\n", sp_name, group_shapes[[sp_name]]))
    }
  } else {
    cat("  No custom shapes defined (all circles)\\n")
  }

  # Get the grouping column (usually species for subspecies coloring)
  # The shape is assigned per species, so we need to map species -> shape
  # Use 'scientific_name' column which contains the species name
  shape_column <- if ("scientific_name" %in% names(points)) "scientific_name" else "species"
  cat(sprintf("  Using column '%s' for shape mapping\\n", shape_column))

  points$shape_code <- sapply(points[[shape_column]], function(sp) {
    shape_name <- group_shapes[[sp]]
    if (is.null(shape_name)) shape_name <- "circle"
    get_shape_code(shape_name)
  })

  # Also add shape column to legend_df for legend rendering
  if ("species" %in% names(legend_df)) {
    legend_df$shape <- sapply(legend_df$species, function(sp) {
      shape_name <- group_shapes[[sp]]
      if (is.null(shape_name)) "circle" else shape_name
    })
  } else {
    legend_df$shape <- "circle"
  }

  cat(sprintf("  Shapes assigned: %d unique shapes\\n", length(unique(points$shape_code))))
  cat(sprintf("  Shape codes in data: %s\\n", paste(unique(points$shape_code), collapse = ", ")))
} else {
  points$shape_code <- 21  # Default to circle
  legend_df$shape <- "circle"
}

# ──────────────────────────────────────────────────────────────────────────────
# 12. BUILD THE MAP
# ──────────────────────────────────────────────────────────────────────────────

cat("\\nCreating map...\\n")

# Start building the plot
p <- ggplot()

# Add basemap layer
if (!is.null(basemap)) {
  p <- p + geom_spatraster_rgb(data = basemap)
} else if (!is.null(basemap_png)) {
  p <- p + annotation_raster(
    basemap_png,
    xmin = bounds$xmin, xmax = bounds$xmax,
    ymin = bounds$ymin, ymax = bounds$ymax
  )
}

# Add data points with stroke (matching web app style)
# If shapes are enabled, use shape aesthetic; otherwise use fixed circle
if (shapes_enabled && "shape_code" %in% names(points)) {
  # Use per-point shapes
  # Note: shape must be mapped to a numeric for filled shapes (21-25)
  p <- p +
    geom_sf(
      data = points,
      aes(fill = display_color, shape = factor(shape_code)),
      color = alpha(STYLE$point_stroke_color, STYLE$point_stroke_alpha),
      size = STYLE$point_size,
      alpha = STYLE$point_alpha,
      stroke = STYLE$point_stroke_width
    ) +
    scale_fill_identity() +
    scale_shape_manual(
      values = c("21" = 21, "22" = 22, "23" = 23, "24" = 24, "25" = 25),
      guide = "none"  # Hide from ggplot's built-in legend (we use custom legend)
    )
} else {
  # Default: all circles
  p <- p +
    geom_sf(
      data = points,
      aes(fill = display_color),
      color = alpha(STYLE$point_stroke_color, STYLE$point_stroke_alpha),
      size = STYLE$point_size,
      alpha = STYLE$point_alpha,
      stroke = STYLE$point_stroke_width,
      shape = 21
    ) +
    scale_fill_identity()
}

# Set coordinate system and bounds
p <- p +
  coord_sf(
    xlim = c(bounds$xmin, bounds$xmax),
    ylim = c(bounds$ymin, bounds$ymax),
    expand = FALSE
  )

# Add scale bar using ggspatial
p <- p +
  annotation_scale(
    location = "br",
    width_hint = 0.15,
    style = "ticks",
    text_col = STYLE$scale_bar_color,
    line_col = STYLE$scale_bar_color,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.5, "cm")
  )

# Apply theme
p <- p +
  theme_void() +
  theme(
    plot.background = element_rect(fill = STYLE$bg_color, color = NA),
    panel.background = element_rect(fill = STYLE$bg_color, color = NA)
  )

# Add custom legend with position, shape, and grouping support
# Use grouped legend if groupBy is set and we have grouping data
if (use_grouped_legend) {
  cat("  Using grouped legend (grouped by species)\\n")
  legend_grob <- create_grouped_legend(
    legend_df,
    legend_groups,
    legend_data$title,
    legend_max_items,
    style = STYLE,
    pos_x = legend_pos_x,
    pos_y = legend_pos_y,
    use_shapes = shapes_enabled,
    show_headers = show_headers,
    display_names = custom_display_names,
    group_shapes = group_shapes
  )
} else {
  cat("  Using flat legend (no grouping)\\n")
  legend_grob <- create_legend(
    legend_df,
    legend_data$title,
    legend_max_items,
    ${isItalic ? 'TRUE' : 'FALSE'},
    style = STYLE,
    pos_x = legend_pos_x,
    pos_y = legend_pos_y,
    use_shapes = shapes_enabled
  )
}

p_final <- p +
  annotation_custom(
    legend_grob,
    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  )

# ──────────────────────────────────────────────────────────────────────────────
# 13. SAVE OUTPUTS
# ──────────────────────────────────────────────────────────────────────────────

cat("\\nSaving outputs...\\n")

# Preview in RStudio
print(p_final)

# Save as PDF (vector graphics for publications)
ggsave("ithomiini_map.pdf", plot = p_final,
       width = output_width, height = output_height, dpi = STYLE$dpi)
cat("  ithomiini_map.pdf\\n")

# Save as high-resolution PNG
ggsave("ithomiini_map.png", plot = p_final,
       width = output_width, height = output_height, dpi = STYLE$dpi)
cat("  ithomiini_map.png\\n")

# Save as SVG (editable vector)
ggsave("ithomiini_map.svg", plot = p_final,
       width = output_width, height = output_height, dpi = STYLE$dpi)
cat("  ithomiini_map.svg\\n")

cat("\\n════════════════════════════════════════════════════════════════════════════════\\n")
cat("Export complete!\\n")
cat("\\nOutput files:\\n")
cat("  ithomiini_map.pdf - Vector PDF for publications\\n")
cat("  ithomiini_map.png - High-resolution raster (300 DPI)\\n")
cat("  ithomiini_map.svg - Editable vector (Adobe Illustrator/Inkscape)\\n")
cat("\\nTip: Edit the STYLE list above to customize colors, sizes, and layout.\\n")
cat("════════════════════════════════════════════════════════════════════════════════\\n")
`
}

export { generateRScript }
