export const LEGEND_LAYOUT = {
  MIN_WIDTH: 200,
  MAX_WIDTH: 600,
  MIN_HEIGHT: 120,
  MIN_SNUG_HEIGHT: 120,
  AUTO_WIDTH_MAX_CONTAINER_RATIO: 0.30,
  MAX_RESIZE_WIDTH_RATIO: 0.45,
  TARGET_HEIGHT_RATIO: 0.75,
  MAX_HEIGHT_RATIO: 0.80,
  MIN_ITEM_HEIGHT_PX: 22,
  FALLBACK_LEGEND_HEIGHT: 200,
  FALLBACK_CONTAINER_HEIGHT: 600,
  STICKY_EDGE_THRESHOLD: 20,
}
